server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8123
          predicates:
#            - Path=/api/name/{api_url}
            - Path=/api/**
          filters: #配置路由过滤器  http://127.0.0.1:8080/product-service/payment/get/1 -> http://127.0.0.1:8001/payment/get/1
            - name: RequestRateLimiter
              args:
                #使用SpEL从容器中获取对象
                key-resolver: "#{@pathKeyResolver}"
                #桶令牌每秒产生平均速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶的上限
                redis-rate-limiter.burstCapacity: 1
#            - RewritePath=/api/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_api
    username: root
    password: root
dubbo:
  application:
    name: dubbo-springboot-nacos-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848


#    address: nacos://localhost:8848